package config

var CustomCityPinyin = map[string]string{
	// === 华北地区 ===
	"石家庄":  "shijiazhuang",
	"保定":   "baoding",
	"唐山":   "tangshan",
	"沧州":   "cangzhou",
	"邯郸":   "handan",
	"邢台":   "xingtai",
	"太原":   "taiyuan",
	"大同":   "datong",
	"呼和浩特": "huhehaote",

	// === 东北地区 ===
	"沈阳":  "shenyang",
	"长春":  "changchun",
	"吉林":  "jilin",
	"哈尔滨": "haerbin",
	"牡丹江": "mudanjiang",
	"鞍山":  "anshan",
	"抚顺":  "fushun",
	"营口":  "yingkou",

	// === 华东地区 ===
	"合肥": "hefei",
	"芜湖": "wuhu",
	"六安": "luan",
	"亳州": "bozhou",
	"巢湖": "chaohu",
	"蚌埠": "bengbu",
	"温州": "wenzhou",
	"嘉兴": "jiaxing",
	"湖州": "huzhou",
	"绍兴": "shaoxing",
	"金华": "jinhua",
	"义乌": "yiwu",
	"衢州": "quzhou",
	"舟山": "zhoushan",
	"台州": "taizhou",
	"丽水": "lishui",
	"乐清": "yueqing",
	"乐山": "leshan",

	// === 福建地区 ===
	"福州": "fuzhou",
	"厦门": "xiamen",
	"泉州": "quanzhou",
	"漳州": "zhangzhou",
	"莆田": "putian",
	"三明": "sanming",
	"宁德": "ningde",
	"龙岩": "longyan",

	// === 珠三角地区 ===
	"广州": "guangzhou",
	"深圳": "shenzhen",
	"佛山": "foshan",
	"东莞": "dongguan",
	"中山": "zhongshan",
	"珠海": "zhuhai",
	"江门": "jiangmen",
	"惠州": "huizhou",
	"汕头": "shantou",
	"湛江": "zhanjiang",
	"茂名": "maoming",

	// === 西南地区 ===
	"成都":  "chengdu",
	"自贡":  "zigong",
	"攀枝花": "panzhihua",
	"泸州":  "luzhou",
	"德阳":  "deyang",
	"绵阳":  "mianyang",
	"广元":  "guangyuan",
	"遂宁":  "suining",
	"内江":  "neijiang",
	"南充":  "nanchong",
	"眉山":  "meishan",
	"宜宾":  "yibin",
	"广安":  "guangan",
	"达州":  "dazhou",
	"雅安":  "yaan",
	"巴中":  "bazhong",
	"资阳":  "ziyang",
	"都江堰": "dujiangyan",
	"重庆":  "chongqing",

	// === 西北地区 ===
	"西安":   "xian",
	"咸阳":   "xianyang",
	"渭南":   "weinan",
	"宝鸡":   "baoji",
	"延安":   "yanan",
	"兰州":   "lanzhou",
	"天水":   "tianshui",
	"银川":   "yinchuan",
	"乌鲁木齐": "wulumuqi",

	// === 华中地区 ===
	"武汉":  "wuhan",
	"宜昌":  "yichang",
	"襄阳":  "xiangyang",
	"荆州":  "jingzhou",
	"岳阳":  "yueyang",
	"长沙":  "changsha",
	"株洲":  "zhuzhou",
	"湘潭":  "xiangtan",
	"衡阳":  "hengyang",
	"常德":  "changde",
	"张家界": "zhangjiajie",
	"怀化":  "huaihua",

	// === 华南地区 ===
	"南宁":  "nanning",
	"桂林":  "guilin",
	"北海":  "beihai",
	"防城港": "fangchenggang",
	"钦州":  "qinzhou",
	"玉林":  "yulin",
	"百色":  "baise",
	"贵港":  "guigang",
	"崇左":  "chongzuo",

	// === 东南沿海 ===
	"温岭": "wenling",

	// === 特殊多音字修正 ===
	"单县": "shanxian",
	"尉犁": "yuli",
	"尉氏": "weishi",
	"句容": "jurong",
	"重慶": "chongqing",
	"称多": "chengduo",
	"蓬莱": "penglai",
}
